parser: babel-eslint
env: es6
extends:
  - prettier
  - prettier/standard
plugins:
  - prettier
rules:
  prettier/prettier: error
  no-unused-vars:
    - error
    - caughtErrorsIgnorePattern: "^_"
  no-console:
    - error
    - allow:
      - warn
      - error
  no-undef: error
  no-const-assign: error
  no-class-assign: error
  constructor-super: error
  no-useless-escape: error
