#!/bin/bash

which eslint_d > /dev/null 2>&1
[[ $? == 1 ]] && npm install -g eslint_d

cd `git rev-parse --show-toplevel`

project_root=$(pwd)

eslint_d start

files=$(git diff --cached --name-only --diff-filter=ACM)
result=$(echo "$files" | grep -e ".js$" | xargs -P20 -n1 eslint_d --fix --format compact \
  | awk '{print $1 $3 $5 $6}' | sed s@${project_root}@\.@)

printf "$result \n"

if [[ $result =~ "Error" ]]; then
  exit 1
fi

eslint_d stop

